name: Deploy to EC2
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
        
      - name: Zip source code
        run: zip -r product_project.zip . -x "*.git*" -x "node_modules/*" -x "dist/*" -x ".github/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Upload  to S3
        run: |
          aws s3 cp product_project.zip s3://your-s3-bucket-name/product_project.zip
        run: |
          ssh -i ${{ secrets.EC2_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/product_project
          npm install
          EOF